import os
import time
from jinja2 import Template

HTML_TEMPLATE = """
<!DOCTYPE html>
<html>
<head>
    <title>NVM Scan Report - {{ target }}</title>
    <style>
        body { font-family: -apple-system, BlinkMacSystemFont, "Segoe UI", Roboto, Helvetica, Arial, sans-serif; margin: 0; padding: 0; background-color: #f4f7f6; }
        .container { width: 90%; margin: 40px auto; background: #ffffff; padding: 30px; border-radius: 8px; box-shadow: 0 4px 12px rgba(0, 0, 0, 0.1); }
        .header { border-bottom: 2px solid #e0e0e0; padding-bottom: 20px; margin-bottom: 30px; }
        h1 { color: #333; margin-top: 0; }
        .badge { display: inline-block; padding: 6px 12px; border-radius: 4px; font-weight: bold; text-transform: uppercase; font-size: 14px; color: white; margin-right: 10px; }
        .risk-HIGH { background-color: #e74c3c; }
        .risk-MEDIUM { background-color: #f39c12; }
        .risk-LOW { background-color: #2ecc71; }
        .risk-NONE { background-color: #95a5a6; }
        .table-container { margin-top: 20px; overflow-x: auto; }
        table { width: 100%; border-collapse: collapse; margin-top: 15px; }
        th, td { padding: 12px 15px; text-align: left; border-bottom: 1px solid #ddd; font-size: 14px; }
        th { background-color: #34495e; color: white; font-weight: 600; }
        tr:hover { background-color: #f8f8f8; }
        .cve-list { font-size: 12px; line-height: 1.6; }
        .cve-id { color: #3498db; text-decoration: none; font-weight: 500; }
    </style>
</head>
<body>
    <div class="container">
        <div class="header">
            <h1>NVM Scan Report: {{ target }}</h1>
            <p><strong>Scan Date:</strong> {{ scan_date }}</p>
            <p><strong>Overall Risk:</strong> <span class="badge risk-{{ overall_risk }}">{{ overall_risk }}</span></p>
        </div>

        <h2>Vulnerability Summary</h2>
        <div class="table-container">
            <table>
                <thead>
                    <tr>
                        <th>Port</th>
                        <th>Service/Version</th>
                        <th>Risk</th>
                        <th>CPE String</th>
                        <th>Vulnerabilities Found</th>
                    </tr>
                </thead>
                <tbody>
                    {% for port, info in results.items() %}
                    <tr>
                        <td><strong>{{ port }}</strong></td>
                        <td>{{ info.service }} ({{ info.version }})</td>
                        <td><span class="badge risk-{{ info.risk }}">{{ info.risk }}</span></td>
                        <td>{{ info.cpe if info.cpe else 'N/A' }}</td>
                        <td>
                            <div class="cve-list">
                            {% if info.vulnerabilities %}
                                {% for vuln in info.vulnerabilities %}
                                    <a class="cve-id" href="https://nvd.nist.gov/vuln/detail/{{ vuln.id }}" target="_blank">{{ vuln.id }}</a> (CVSS: {{ vuln.cvss_v3 }})<br>
                                {% endfor %}
                            {% else %}
                                None found.
                            {% endif %}
                            </div>
                        </td>
                    </tr>
                    {% endfor %}
                </tbody>
            </table>
        </div>
        <p style="margin-top: 50px; text-align: center; color: #7f8c8d;">Report generated by NVM v1.0 (Network Vulnerability Manager)</p>
    </div>
</body>
</html>
"""

def create_html_report(overall_risk, final_results, target):
    template = Template(HTML_TEMPLATE)
    
    # We convert the dictionary keys to strings to make them available in Jinja2 iteration
    # Since final_results is already a dictionary, we just need to pass the context.

    rendered_html = template.render(
        target=target,
        scan_date=time.strftime("%Y-%m-%d %H:%M:%S"),
        overall_risk=overall_risk,
        results=final_results
    )
    
    filename = f"NVM-Report-{target}.html"
    filepath = os.path.join("reports", filename)
    
    if not os.path.exists("reports"):
        os.makedirs("reports")
        
    with open(filepath, 'w', encoding='utf-8') as f:
        f.write(rendered_html)
        
    return filename